version: 0.0
os: linux
files:
  - source: /components/server
    destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: /components/server/scripts/startServer
      timeout: 900
      runas: root
