version: 0.2

phases:
  build:
    commands:
      - cd components/server
      - npm install
      - npm run migrate-prod
      # - npm run compile
      - npm run setup-integration-tests
      - npm run integration-test
artifacts:
  files:
    - "**/*"
  base-directory: "components/server"
#     base-directory: 'components/server'
