version: 0.2

phases:
  build:
    commands:
      - cd components/server
      - npm install
      # - npm run compile
      - npm run setup-integration-tests
      - npm run integration-test
artifacts:
  files:
    - "**/server/"
#     base-directory: 'components/server'
